import contact_link from "./../assets/icons/contact.svg";
import cpp_link from "./../assets/icons/cpp.svg";
import docker_link from "./../assets/icons/docker.svg";
import express_link from "./../assets/icons/express.svg";
import git_link from "./../assets/icons/git.svg";
import github_link from "./../assets/icons/github.svg";
import java_link from "./../assets/icons/java.svg";
import javascript_link from "./../assets/icons/javascript.svg";
import linkedin_link from "./../assets/icons/linkedin.svg";
import maven_link from "./../assets/icons/maven.svg";
import mongodb_link from "./../assets/icons/mongodb.svg";
import nodejs_link from "./../assets/icons/nodejs.svg";
import python_link from "./../assets/icons/python.svg";
import react_link from "./../assets/icons/react.svg";
import scikit_learn_link from "./../assets/icons/scikit_learn.svg";
import springboot_link from "./../assets/icons/springboot.svg";
import sql_link from "./../assets/icons/sql.svg";
import sqlserver_link from "./../assets/icons/sqlserver.svg";
import typescript_link from "./../assets/icons/typescript.svg";

import tictactoe_route from "./../assets/icons/tictactoe.svg";
import compression_route from "./../assets/icons/compression.svg";
import plane_route from "./../assets/icons/plane.svg";
import speaker_route from "./../assets/icons/speaker.svg";
import route_route from "./../assets/icons/route.svg";
import container_route from "./../assets/icons/container.svg";
import game_route from "./../assets/icons/game.svg";
import job_route from "./../assets/icons/job.svg";


export const contact = contact_link;
export const cpp = cpp_link;
export const docker = docker_link;
export const express = express_link;
export const git = git_link;
export const github = github_link;
export const java = java_link;
export const javascript = javascript_link;
export const linkedin = linkedin_link;
export const maven = maven_link;
export const mongodb = mongodb_link;
export const nodejs = nodejs_link;
export const python = python_link;
export const react = react_link;
export const scikit_learn = scikit_learn_link;
export const springboot = springboot_link;
export const sql = sql_link;
export const sqlserver = sqlserver_link;
export const typescript = typescript_link;

export const tictactoe = tictactoe_route;
export const compression = compression_route;
export const plane = plane_route;
export const speaker = speaker_route;
export const route = route_route;
export const container = container_route;
export const game = game_route;
export const job = job_route;