AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deploy the backend lambdas my personal portfolio project

Parameters:
<<<<<<< HEAD
=======
  AWS_ROLE_ARN:
    Type: String
    NoEcho: true

>>>>>>> a0bdac05dd0628cc75d203906413b009224b4d11
  LAMBDA_EXECUTION_ROLE_ARN:
    Type: String
    NoEcho: true

Globals:
  Function:
    Timeout: 50
    MemorySize: 256
    Runtime: python3.13
    Architectures:
      - x86_64
    Tracing: Active

Resources:
  portfolio-api:
    Type: AWS::Serverless::Api
    Properties:
      Name: portfolio-api
      StageName: prod
      MethodSettings:
        - ResourcePath: "/*"
          HttpMethod: "*"
          ThrottlingRateLimit: 2
          ThrottlingBurstLimit: 5

      Cors:
        AllowOrigin: "'https://laughcheeta1.github.io/PersonalPortfolio/'"
        AllowMethods: "'POST,OPTIONS'"
        AllowHeaders: "'content-type'"

      EndpointConfiguration: REGIONAL
      

  chatbot_lambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: chatbot_lambda
      CodeUri: src/chatbot
      Handler: app.lambda_handler
      ReservedConcurrentExecutions: 5
      Role: !Ref LAMBDA_EXECUTION_ROLE_ARN

      Environment:
        Variables:
          GROQ_API_KEY: {{resolve:secretsmanager:GROQ_API_KEY:SecretString:GROQ_API_KEY}}

      Events:
        ChatRoute:
          Type: Api
          Properties:
            RestApiId: !Ref portfolio-api
            Path: /chat
            Method: POST

Outputs:
  ApiUrl:
    Description: "The api gateway endpoint url"
    Value: !Sub "https://${portfolio-api}.execute-api.${AWS::Region}.amazonaws.com/prod/chat"
