name: Deploy Personal Portfolio

on:
  workflow_dispatch:
  push:
    branches: ["master"]
    paths:
      - "frontend/**"
      - "lambdas/**"
      - ".github/workflows/deploy.yaml"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy-lambdas:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lambdas

    outputs:
      api_url: ${{ steps.cfn.outputs.api_url }}
    
    steps:
      - name: Download the repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Built the sam file
        run: sam build

      - name: Deploy Sam
        run: |
          sam deploy \
            --stack-name ${{ secrets.SAM_STACK_NAME }} \
            --resolve-s3 \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --parameter-overrides LAMBDA_EXECUTION_ROLE_ARN=${{ secrets.LAMBDA_EXECUTION_ROLE_ARN }}

      - name: Read Api Gateawy url
        id: cfn
        run: |
          API_URL=$(aws cloudformation describe-stacks \
            --stack-name ${{ secrets.SAM_STACK_NAME }} \
            --query "Stacks[0].Outputs[?OutputKey=='ApiUrl'].OutputValue" \
            --output text)
          
          echo "api_url=$API_URL" >> "$GITHUB_OUTPUT"

  build-frontend:
    runs-on: ubuntu-latest
    needs: deploy-lambdas
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Download repo
        uses: actions/checkout@v4

      - name: Set the API_URL env for the front end
        run: |
          echo "VITE_API_URL=${{ needs.deploy-lambdas.outputs.api_url }}" >> $GITHUB_ENV
      
      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.3.9"
      
      - name: Add bun to path
        run: echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Cache Bun downloads
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('frontend/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Cache Vite cache
        uses: actions/cache@v4
        with:
          path: |
            frontend/node_modules/.vite
          key: ${{ runner.os }}-vite-${{ hashFiles('frontend/vite.config.*', 'frontend/package.json', 'frontend/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-vite-

      - name: Build the project
        run: bun run build

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/dist
  
  deploy-frontend:
    needs: build-frontend
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to github pages
        id: deployment
        uses: actions/deploy-pages@v4
